// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://ntuowqvlxfhboizchnol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im50dW93cXZseGZoYm9pemNobm9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjQwNjU5MDUsImV4cCI6MjA3OTY0MTkwNX0.ig97uNPVrYOqkVeUAMN8kRLtM3zDWopdukrAb4JRV3U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);